# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
theme: JBlog
# Site settings
title: Boo the Buhund
email: endsoftheearthdev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here's a website about a buhund named Boo. Forged by Bokkr and blessed by  Baldur, 
  she is an unstoppable force of relentless fury and furry. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://boothebuhund.com" # the base hostname & protocol for your site
twitter_username: earthsends
github_username:  endsoftheearthdev

# Build settings
markdown: kramdown
